version: '3'

services:

    app:
        build: .
        container_name: bitzen-teste-raylsonlima
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=testesrh.bitzen.com.br
            - _DB_DATABASE=raylson_lima
            - _DB_USERNAME=raylson_lima
            - _DB_PASSWORD=psQW8UEjkQd4
        volumes:
            - .:/var/www
        networks:
            - app-network

    nginx:
        build: .docker/nginx
        container_name: nginx-server
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
